### PR TITLE
Fix locking

### PR DESCRIPTION
**Pull request by ktf**
Fix locking

### CODE REVIEW

**Comment by ktf** [comment]
GCC 13 complains about the move to itself, and indeed it does not make sense to me. Is what I have in this PR the intended behavior?

**Comment by ktf** [comment]
If yes, can you please merge, tag, and update alidist?

**Comment by ktf** [comment]
@kostorr could you have a look?

**Comment by ktf** [comment]
@sy-c I was told this is your domain. Can you have a look?

**Comment by sy-c** [comment]
Sure, I will check this today.

**Pull request merged**
